name: Publish NPM package and Release on GitHub
on:
  push:
    branches:
      - master
jobs:
  publish:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
           registry-url: https://registry.npmjs.org/
      - id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
      - if: steps.check.outputs.changed == 'true'
        run: |
          npm install
          npm publish